<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Truy cp vo lin kt</name>
   <tag></tag>
   <elementGuidId>c2f812c3-dbeb-499f-8b76-c8b75f52210d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#u_0_b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='u_0_b']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_42ft _42fu selected _42g-</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://l.facebook.com/l.php?u=https%3A%2F%2Fkatalon-demo-cura.herokuapp.com%2F%3Ffbclid%3DIwAR2FPHNSQBq6aZhGIJAUI9jcZiECVyjDHmtgsJMD4m2CQlh0rFYQ86rpaIQ&amp;h=AT3bQq2jBcP17SZ54ne0t6EmaeJojXIAlTA1QqgEdH-WKiGJ7TyLQ7JdpC84iFeJ4_zUAHlLBg79WeDwmcidMRjH5AwwcXmHNGqZK-SGertVcXeu3APfBEWeir6XUgGaGbf_NKa_fE3Acshe0c65HjmqQSOkJgq-5PBUnYyEGcIgUddcKKNa65CYdlhEwr5-QSOJzirE6UgyTgGorcH0qt68GtHjdQ1B1C2IDsyHncaEH0zkyfgasn-RWC4VBMNw8xAZ6g7ZoqhsBaeHa8zXmPvw_FtiaJA_Vd_QFQz5Aw8Abg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_b</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Truy cập vào liên kết</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_b&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='u_0_b']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_0_9']/div/div[3]/a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Truy cập vào liên kết')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quay lại'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiếng Việt'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English (UK)'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Truy cập vào liên kết']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://l.facebook.com/l.php?u=https%3A%2F%2Fkatalon-demo-cura.herokuapp.com%2F%3Ffbclid%3DIwAR2FPHNSQBq6aZhGIJAUI9jcZiECVyjDHmtgsJMD4m2CQlh0rFYQ86rpaIQ&amp;h=AT3bQq2jBcP17SZ54ne0t6EmaeJojXIAlTA1QqgEdH-WKiGJ7TyLQ7JdpC84iFeJ4_zUAHlLBg79WeDwmcidMRjH5AwwcXmHNGqZK-SGertVcXeu3APfBEWeir6XUgGaGbf_NKa_fE3Acshe0c65HjmqQSOkJgq-5PBUnYyEGcIgUddcKKNa65CYdlhEwr5-QSOJzirE6UgyTgGorcH0qt68GtHjdQ1B1C2IDsyHncaEH0zkyfgasn-RWC4VBMNw8xAZ6g7ZoqhsBaeHa8zXmPvw_FtiaJA_Vd_QFQz5Aw8Abg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
   </webElementXpaths>
</WebElementEntity>
